name: Run Unit Tests

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest # GitHub Actions runner to use for the job (ubuntu-latest, windows-latest, macOS-latest)

        steps:
            - name: Check out repsitory code # Check out the repository code to the runner
              uses: actions/checkout@v3 # GitHub Actions to use for the step (actions/checkout@v3) 

            - name: Set up Pyhton environment # Set up the Python environment for the job
              uses: actions/setup-python@v4 # GitHub Actions to use for the step (actions/setup-python@v4)
              with:
                  python-version: '3.12.6'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                python -m unittest discover
